### ISSUE TITLE
Extra Properties in resource net show as not valid

### ISSUE THREAD

**Issue by Makr91** [omniosorg/zadm#116]
Hello All,

After getting pfSense to work in CARP using the e1000 interfaces using zonecfg, I generally use zadm noVNC or zlogin or zadm to access the zone. When I use zadm I am getting this warning:

I was told this is how I should configure these settings in zonecfg for promiscuous, mac spoofing and other flags:

Warning:
![image](https://user-images.githubusercontent.com/11012628/157431177-7373adc4-d1af-443a-84d5-b43e42c371ca.png)

example zonecfg: 

```
zonename: 1014--firewall-04.dc-01.m4kr.net
zonepath: /Array-0/zones/1014--firewall-04.dc-01.m4kr.net/path
brand: bhyve
autoboot: true
bootargs:
pool:
limitpriv:
scheduling-class:
ip-type: exclusive
hostid:
fs-allowed:
net:
        address not specified
        allowed-address not specified
        defrouter not specified
        global-nic not specified
        mac-addr not specified
        physical: vnice3_1014_0
        vlan-id not specified
        property: (name=promiscphys,value="on")
        property: (name=allow_ip_spoofing,value="true")
        property: (name=allow_mac_spoofing,value="true")
net:
        address not specified
        allowed-address not specified
        defrouter not specified
        global-nic not specified
        mac-addr not specified
        physical: vnici3_1014_0
        vlan-id not specified
        property: (name=promiscphys,value="on")
        property: (name=allow_ip_spoofing,value="true")
        property: (name=allow_mac_spoofing,value="true")
net:
        address not specified
        allowed-address not specified
        defrouter not specified
        global-nic not specified
        mac-addr not specified
        physical: vnicc3_1014_0
        vlan-id not specified
device:
        match: /dev/zvol/rdsk/Array-0/zones/1014--firewall-04.dc-01.m4kr.net/boot
attr:
        name: acpi
        type: string
        value: true
attr:
        name: ram
        type: string
        value: 8G
attr:
        name: bootrom
        type: string
        value: BHYVE_RELEASE
attr:
        name: hostbridge
        type: string
        value: i440fx
attr:
        name: diskif
        type: string
        value: virtio-blk
attr:
        name: bootdisk
        type: string
        value: Array-0/zones/1014--firewall-04.dc-01.m4kr.net/boot
attr:
        name: type
        type: string
        value: generic
attr:
        name: vcpus
        type: string
        value: 4
attr:
        name: vnc
        type: string
        value: on
attr:
        name: netif
        type: string
        value: e1000

```
