### ISSUE TITLE
relax validation on bhyve networking

### ISSUE THREAD

**Issue by sjorge** [omniosorg/zadm#151]
I want to use a dedicated HW nic for a bhyve VM, according to @citrus-it this should work TM but wasn't tested.

It works! But you can't do it with zadm :(

```
zonecfg -z carp2
> add net
> set physical=igb2
> end
> exit
```

If you try to boot the vm now it fails, as virtio-net-viona cannot open the special backing device that gets created with a vnic.
But you can set netif to e1000 and it will work! (virtio-net also works, the non viona virtio variant)

```
zonecfg -z carp2
> select attr name=netif
> set value=e1000
> end
> exit
```

You can now boot the VM, the resulting config is this:
```
#
# Generated from zone configuration
#
acpi_tables=false
acpi_tables_in_memory=true
memory.size=1G
memory.use_reservoir=true
x86.strictmsr=true
x86.vmexit_on_hlt=true
lpc.fwcfg=bhyve
lpc.com1.path=/dev/zconsole
uuid=029b8731-d609-486a-ae57-75e848abc3af
system.manufacturer=OmniOS
system.product_name=OmniOS HVM
system.version=1.0
system.serial_number=029b8731-d609-486a-ae57-75e848abc3af
system.sku=001
system.family_name=Virtual Machine
cpus=1
sockets=1
cores=1
threads=1
bootrom=/usr/share/bhyve/firmware/BHYVE_RELEASE.fd
bootvars=/etc/uefivars
pci.0.0.0.device=hostbridge
pci.0.0.0.model=i440fx
pci.0.1.0.device=lpc
pci.0.4.0.device=nvme
pci.0.4.0.path=/dev/zvol/rdsk/rpool/vms/carp2/disk0
pci.0.6.0.device=e1000
pci.0.6.0.backend=dlpi
pci.0.6.0.type=dlpi
pci.0.6.0.vnic=igb2
name=carp2
```

Notice the:
```
pci.0.6.0.backend=dlpi
pci.0.6.0.type=dlpi
```

With the VM not booted:
```
root@saturn:~# dladm show-phys igb2
LINK         MEDIA                STATE      SPEED    DUPLEX   DEVICE
igb2         Ethernet             unknown    1000     full     igb2
```

After booting the VM:
```
root@saturn:~# dladm show-phys igb2
LINK         MEDIA                STATE      SPEED    DUPLEX   DEVICE
igb2         Ethernet             up         1000     full     igb2
```

Of course linkprop's like MTU and things need to be set before booting the vm but the host remembers these because they end up in dladm.conf.

It would be nice to have zadm not error when editing the VM or when trying to set it up like this:

```
root@saturn:~# zadm show carp2
---
acpi: on
autoboot: 'false'
bootargs: ''
bootdisk:
  blocksize: 4K
  path: rpool/vms/carp2/disk0
  size: 15G
  sparse: 'false'
bootorder:
- cd
bootrom: BHYVE_RELEASE
brand: bhyve
capped-cpu:
  ncpus: '1.50'
cloud-init: off
diskif: nvme
fs-allowed: ''
hostbridge: i440fx
hostid: ''
ip-type: exclusive
limitpriv: default
memreserve: on
net:
- physical: igb2
netif: e1000
pool: ''
ram: 1G
rng: off
scheduling-class: ''
type: generic
uefivars: on
vcpus: 1,sockets=1,cores=1,threads=1
vga: off
vnc:
  enabled: off
xhci: off
zonename: carp2
zonepath: /zones/carp2
```

If you try to edit it:
```
root@saturn:~# zadm edit carp2
dladm: vnic creation over ixgbe0 failed: object already exists
root->net: Execution of validator for 'physical' returns with error: ERROR: executing 'dladm':

Do you want to retry [Y/n]?
```

Due to the lack of global-nic it tries to add it and default it to ixgbe0 in my case, it then fails to create a vnic with the name igb2 because that device already exists.

At the very lease I think we should be able to edit the VM without it complaining.
